### ISSUE TITLE
Issues with build

### ISSUE THREAD

**Issue by samrose** [JuliaCN/Julia2Nix.jl#52] opened 2023-05-08 13:54 UTC
I have this project

https://github.com/fractal-dynamics/powersim

When I try to build it with julia2nix I am seeing this error

https://gist.github.com/samrose/d8d57b2daa63bc2f5e8c96a53b31f1f8

Is this a case where a package someone made is trying to reach out and download during the sandbox phase of nix build?

**Comment by GTrunSec** [comment] 2023-05-08 14:25
You can use the `extraDepot` to download the artifacts manually.
https://github.com/JuliaCN/Julia2Nix.jl/blob/main/nix/julia2nix/entrypoints/default.nix#L36
Since I only have a little time to maintain this repo, the rewrite plan has been shelved for a long time.

**Comment by samrose** [comment] 2023-05-08 18:28
thanks for the pointers. I think it may be that julia2nix.jl very usable as it is, and in my case it's just becoming familiar with using it.

**Comment by samrose** [comment] 2023-05-08 18:29
@GTrunSec  are there ways us users can help you maintain the repo?

**Comment by GTrunSec** [comment] 2023-06-02 22:58
@samrose We should discuss how to refactor the julia2nix and what kind of roadmap we have.
For current maintenance, we are just required to replace nix-prefect with nix-prefect-git etc. as https://github.com/berberman/nvfetcher/commit/d3226cb40df74dd6b432d5ce15bbcb05f3825ce2 did.

**Comment by samrose** [comment] 2023-06-02 23:17
Hi I’ll catch up with you next week on this. Thank you for looping me in. I’ll check out the commit above

**Comment by GTrunSec** [comment] 2023-06-02 23:27
@samrose  Great, with your help, I can focus on how to build the DevOps ecosystem for data-science. I expect to have powerful dataOps and research lab support soon.
- https://github.com/GTrunSec/dataflow2nix/tree/main/nix [platforms]
- https://github.com/GTrunSec/deSci/tree/main/nix (jupyterlab/kernelsEnv/ dataOps/MLOps)
- https://gtrunsec.github.io/desci-workflow-template/  [publish our julia/python notebook to quarto website]
   * reproducible 100% for the research process.

**Comment by samrose** [comment] 2023-06-29 13:09
@GTrunSec I'll start looking into this as time permits now, sorry for the radio silence on my part

**Comment by samrose** [comment] 2023-06-29 13:16
@GTrunSec I am not actually seeing nix-prefect anywhere in this repo?

**Comment by samrose** [comment] 2023-08-03 20:11
@GTrunSec just checking in with you again on the above. Seeing if there is a way I can contribute. Thanks!

**Comment by GTrunSec** [comment] 2023-08-04 03:39
@samrose, sorry for the late reply; I was busy and still waiting for https://github.com/NixOS/nixpkgs/pull/225513 to be done and merged. 
Let me write a roadmap tomorrow, and we should base it on https://github.com/NixOS/nixpkgs/pull/225513 to refactor our code.
We already have https://github.com/codedownio/General, so there will be less work to build a project even without generating that julia2nix.toml.(if LFD is allowed)
Also, we can drop the nix-prefetch off totally, then simply transfer the `git_tree-hash` to `nix-hash` enough(only for the `custom_fetcher_link` and `private_repo`). #42

**Closed as completed** 2023-10-31 10:49 UTC
